version: "3"

services:
  banner-db:
    image: postgres:14.2
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=banner_db
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    #  - ./postgres/schemas:/docker-entrypoint-initdb.d/banner_db.sql
     # - ./postgres/data/initial_data.sql:/docker-entrypoint-initdb.d/initial_data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d banner_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    networks:
      - application

  banner-service-go:
    image: banner_service_go
    depends_on:
      banner-db:
        condition: service_healthy
    networks:
      - application
    ports:
      - "8080:8080"
    restart: on-failure

networks:
  application:
    driver: bridge
